#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 04 23:35:08 EST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 692a7de9f6314f0a8b6a6845f2b08232 --incr --debug typical --relax --mt 8 -L blk_mem_gen_v8_4_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mock_photon_signal_tb_behav xil_defaultlib.mock_photon_signal_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 692a7de9f6314f0a8b6a6845f2b08232 --incr --debug typical --relax --mt 8 -L blk_mem_gen_v8_4_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mock_photon_signal_tb_behav xil_defaultlib.mock_photon_signal_tb xil_defaultlib.glbl -log elaborate.log

